POST localhost:8081/auth/registration
Content-Type: application/json

{
  "username": "lockbeck1",
  "email": "1t.lochin.98@gmail.com",
  "password": "123"
}

###
POST localhost:8080/auth/login
Content-Type: application/json

{
  "username": "lock",
  "password": "333"
}

###
GET localhost:8080/auth/resend/t.lochin.98@gmail.com
