POST http://localhost:8080/channel/public/create
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTc5MjgzOTYsImV4cCI6MTY1NzkzMTk5NiwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjo3fQ.e5bqHXXTiWsGKYjXUU9yL6AOvSVdsI9YCiarI5aGe5A
Content-Type: application/json

{
  "name": "pubg",
  "description": "zor kanal",
  "photoId": "cacbb5cb-b8de-4d4c-b37b-739c9f161fd0"
}

###

PUT http://localhost:8080/channel/public/update/4028e4b882043cee0182043d49b10000
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTc5MjgzOTYsImV4cCI6MTY1NzkzMTk5NiwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjo3fQ.e5bqHXXTiWsGKYjXUU9yL6AOvSVdsI9YCiarI5aGe5A
Content-Type: application/json

{
  "name": "pubg",
  "description": "zor kanal",
  "photoId": "60789089-5478-43fd-a929-7cff8b9b1e3d"
}

###
DELETE http://localhost:8080/category/adm/delete/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTc5MDg2NjUsImV4cCI6MTY1NzkxMjI2NSwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoxfQ.Olt5zzmzl8ZdXQQ9PplwhH5j95k5rb-axE6_kc5qbLc

###
GET http://localhost:8080/category/public/getAll